/** Nontechnical visual model labels and distinct livery styling for Iranian ballistic/hypersonic missiles. */
export const MISSILE_MODELS = [
  {
    id: "kheibar",
    label: "خیبرشکن",
    colorName: "خاکستری فیلی تاکتیکی",
    colorHex: "#c5beaf",
    metalness: 0.58,
    roughness: 0.32,
    textColor: "#000000",
    fuelColor: "#f59e0b",
    fuelEmissive: "#d97706",
    fuelName: "طلایی کهربایی معنوی",
    caption: "فرم تاکتیکی · بالک‌های هدایت میانی · رنگ فیلی تیتانیومی",
  },
  {
    id: "fattah",
    label: "فتاح ۱",
    colorName: "قهوه‌ای دارک متالیک",
    colorHex: "#2e211b",
    metalness: 0.52,
    roughness: 0.42,
    textColor: "#ffffff",
    fuelColor: "#ef4444",
    fuelEmissive: "#b91c1c",
    fuelName: "سرخ پلاسما هایپرسونیک",
    caption: "هایپرسونیک · کلاهک گلایدری دو مخروطه · رنگ قهوه‌ای تیره مات",
  },
  {
    id: "sejjil",
    label: "سجیل",
    colorName: "قهوه‌ای خاکی کویری",
    colorHex: "#835a38",
    metalness: 0.48,
    roughness: 0.38,
    textColor: "#ffffff",
    fuelColor: "#f97316",
    fuelEmissive: "#c2410c",
    fuelName: "نارنجی قرمز آتشین سوخت جامد",
    caption: "دوربرد سوخت جامد · دو مرحله‌ای با رینگ‌های طلایی · رنگ قهوه‌ای خاکی",
  },
  {
    id: "khorramshahr",
    label: "خرمشهر ۴",
    colorName: "قهوه‌ای برنزه دودی",
    colorHex: "#524336",
    metalness: 0.55,
    roughness: 0.36,
    textColor: "#ffffff",
    fuelColor: "#eab308",
    fuelEmissive: "#a16207",
    fuelName: "برنز گداخته و مس تابان",
    caption: "سرجنگی سنگین · دماغه مخروطی پهن · رنگ قهوه‌ای برنزه دودی",
  },
  {
    id: "emad",
    label: "عماد",
    colorName: "سفید بالستیک نقطه‌زن",
    colorHex: "#e2e8f0",
    metalness: 0.52,
    roughness: 0.34,
    textColor: "#0f172a",
    fuelColor: "#06b6d4",
    fuelEmissive: "#0e7490",
    fuelName: "فیروزه‌ای نئونی هدایت نقطه‌زن",
    caption: "نقطه‌زن دوربرد · بالک‌های هدایت سرجنگی کلاهک · رنگ سفید متالیک",
  },
  {
    id: "reyhaneh",
    label: "ریحانه (دخترانه)",
    colorName: "صورتی پاستلی کارتونی",
    colorHex: "#f472b6",
    metalness: 0.38,
    roughness: 0.28,
    textColor: "#ffffff",
    fuelColor: "#ec4899",
    fuelEmissive: "#be185d",
    fuelName: "صورتی جادویی درخشان",
    caption: "طرح اختصاصی ریحانه · رنگ صورتی شاد با برچسب‌های قلبی، پروانه و گل‌های کارتونی",
  },
  {
    id: "shahed136",
    label: "پهپاد شاهد ۱۳۶",
    colorName: "طوسی تاکتیکی مات دلتا",
    colorHex: "#3f4756",
    metalness: 0.28,
    roughness: 0.68,
    textColor: "#f8fafc",
    fuelColor: "#10b981",
    fuelEmissive: "#059669",
    fuelName: "سبز راداری زمردی",
    caption: "پهپاد بال دلتا انتحاری · پشتیبانی از پرتاب رگباری صلواتی یا سوخت‌گیری و انفجار نهایی",
  },
] as const;

export type MissileModel = (typeof MISSILE_MODELS)[number]["id"];
export type MissileVisualConfig = (typeof MISSILE_MODELS)[number];

export function getMissileConfig(id: string): MissileVisualConfig {
  const found = MISSILE_MODELS.find((m) => m.id === id);
  return found ?? MISSILE_MODELS[0];
}
